#                                                                        #
# Settings                                                               #
#                                                                        #
# This file contains settings for various parts of the application.      #
# Just add your own modifications as necessary.                          #
#                                                                        #
# Please refer to the default settings file(s) or the manuals for        #
# possible configuration options.                                        #
#                                                                        #

TYPO3:
  Setup:
    initialPasswordFile: '%FLOW_PATH_DATA%SetupPassword.txt'
    stepOrder:
      - database
      - final
    steps:
      database:
        className: Neos\Setup\Step\DatabaseStep
        requiredConditions:
          -
            className: Neos\Setup\Condition\PdoDriverCondition
      final:
        className: Neos\Setup\Step\FinalStep
    view:
      title: Setup
    http:
      chain:
        preprocess:
          chain:
            configureRouting:
              position: start
              component: Neos\Setup\Core\ConfigureRoutingComponent
  Form:
    presets:
      typo3.setup:
        title: 'Setup Elements'
        parentPreset: default
        formElementTypes:
          'TYPO3.Form:Base':
            renderingOptions:
              layoutPathPattern: 'resource://Neos.Setup/Private/Form/Layouts/{@type}.html'
              validationErrorTranslationPackage: Neos.Flow
          'TYPO3.Form:Form':
            renderingOptions:
              templatePathPattern: 'resource://Neos.Setup/Private/Form/{@type}.html'
          'Neos.Setup:LinkElement':
            superTypes:
              - 'TYPO3.Form:ReadOnlyFormElement'
            properties:
              text: ''
              class: btn
              href: ''
          'Neos.Setup:DatabaseSelector':
            superTypes:
              - 'TYPO3.Form:FormElement'
            properties:
              elementClassAttribute: form-control
          'TYPO3.Form:SingleLineText':
            properties:
              elementClassAttribute: form-control
          'TYPO3.Form:Password':
            properties:
              elementClassAttribute: form-control
          'TYPO3.Form:PasswordWithConfirmation':
            renderingOptions:
              templatePathPattern: 'resource://Neos.Setup/Private/Form/{@type}.html'
            properties:
              elementClassAttribute: form-control
              confirmationClassAttribute: form-control
          'TYPO3.Form:Checkbox':
            renderingOptions:
              templatePathPattern: 'resource://Neos.Setup/Private/Form/{@type}.html'
            properties:
              elementClassAttribute: checkbox
          'TYPO3.Form:MultipleSelectDropdown':
            properties:
              elementClassAttribute: form-control
          'TYPO3.Form:SingleSelectDropdown':
            renderingOptions:
              templatePathPattern: 'resource://Neos.Setup/Private/Form/{@type}.html'
          'TYPO3.Form:StaticText':
            renderingOptions:
              templatePathPattern: 'resource://Neos.Setup/Private/Form/{@type}.html'
Neos:
  Flow:
    security:
      authentication:
        providers:
          Typo3SetupProvider:
            provider: FileBasedSimpleKeyProvider
            providerOptions:
              keyName: SetupKey
              authenticateRoles:
                - 'Neos.Setup:SetupUser'
            requestPatterns:
              'Neos.Setup:controllerObjectName':
                pattern: ControllerObjectName
                patternOptions:
                  controllerObjectNamePattern: 'Neos\Setup\Controller\.*|Neos\Setup\ViewHelpers\Widget\Controller\.*'
            entryPoint: WebRedirect
            entryPointOptions:
              uri: setup/login
